### ISSUE TITLE
[Chat] 채팅 구현

### ISSUE THREAD

**Issue by jungeun919** [transcendence-42seoul/transcendence_back#24]
## 📃 Description
채팅 기능 구현

## ☑ Todo
- [x] 채팅 관련 스키마 설계
- [x] 채팅방 생성 (public/private/dm)
- [x] 채팅방 조인, 삭제
- [x] 채팅 메시지 저장 구현
