### ISSUE TITLE
[Chat] connect socket

### ISSUE THREAD

**Issue by jungeun919** [transcendence-42seoul/transcendence_back#32]
## 📃 Description
채팅 소켓 연결

## ☑ Todo
- [x] 채팅 채널 참여, socket room 참여
- [x] 채팅 채널 생성
- [x] room id로 메시지 전송
- [x] 채널 나가기
