### ISSUE TITLE
[Chat] channel password

### ISSUE THREAD

**Issue by jungeun919** [transcendence-42seoul/transcendence_back#42]
## 📃 Description
채널 패스워드 관련 CRUD

## ☑ Todo
- [x] 방 생성 후 방장이 패스워드 생성 (public -> private)
- [x] 방 생성 후 방장이 패스워드 수정
- [x] 방 생성 후 방장이 패스워드 제거 (private -> public)
